---
- hosts: centos
  tasks:
    - name: Install the nodejs
      yum:
        name: nodejs
        state: present
      become: yes
      when: ansible_os_family == 'RedHat'

    - template:
        src: hello.js
        dest: /root
        owner: root
        group: root
        mode: 0644
      become: yes
      when: ansible_os_family == 'RedHat'

    - name: install pm2
      command: bash -lc "cd /root &&  npm install pm2 -g"
      become: yes
      when: ansible_os_family == 'RedHat'
    
    - name: start server
      command: bash -lc "cd /root && pm2 start hello.js"
      become: yes
      when: ansible_os_family == 'RedHat'

    - name: stop server
      command: bash -lc "cd /root && pm2 stop hello.js"
      become: yes
      when: ansible_os_family == 'RedHat'

    - name: start server
      command: bash -lc "cd /root && pm2 start hello.js"
      become: yes
      when: ansible_os_family == 'RedHat'
- hosts: ubuntu
  tasks:
    - name: Install the nodejs
      apt:
        name: nodejs
        state: present
      become: yes
      when: ansible_os_family == 'Debian'

    - template:
        src: hello.js
        dest: /root
        owner: root
        group: root
        mode: 0644
      become: yes
      when: ansible_os_family == 'Debian'


    - name: update
      command: bash -lc "cd /root &&  apt-get update -y"
      become: yes
      when: ansible_os_family == 'Debian'

    - name: Install the npm
      apt:
        name: npm
        state: present
      become: yes
      when: ansible_os_family == 'Debian'
      
    - name: start server
      command: bash -lc "cd /root && pm2 start hello.js"
      become: yes
      when: ansible_os_family == 'Debian'

      - name: stop server
      command: bash -lc "cd /root && pm2 stop hello.js"
      become: yes
      when: ansible_os_family == 'Debian'

    - name: install pm2
      command: bash -lc "cd /root && npm install pm2 -g"
      become: yes
      when: ansible_os_family == 'Debian'

    - name: start server
      command: bash -lc "cd /root && pm2 start hello.js"
      become: yes
      when: ansible_os_family == 'Debian'
- hosts: win
  tasks:
  roles:
    - { role: chocolatey, when: "ansible_os_family == 'Windows'" }

  tasks:
    - name: Install nodejs
      win_command: powershell.exe choco install nodejs -y
      when: ansible_os_family == 'Windows'

    - name: copy hello.js
      win_copy:
        src: /root/templates/hello.js
        dest: C:\Program Files\nodejs\hello.js
        when: ansible_os_family == 'Windows'

   - name: stop hello.js
      win_command: powershell.exe Stop-Process -processname node*
      when: ansible_os_family == 'Windows'

    - name: install npm
      win_command: powershell.exe npm install
      when: ansible_os_family == 'Windows'

    - name: install pm2
      win_command: powershell.exe npm install pm2 -g
      when: ansible_os_family == 'Windows'

    - name: start hello.js
      win_command: powershell.exe pm2 start hello.js
      when: ansible_os_family == 'Windows'
